name: Bug Report  
description: Report a bug in the project  
title: "[Bug] "  
labels: ["bug"]  
body:
  - type: markdown  
    attributes:
      value: "Thanks for reporting this issue! Please fill in the details below."
  - type: input  
    id: bug-summary  
    attributes:
      label: "Bug Summary"
      placeholder: "Briefly describe the issue"
    validations:
      required: true  
  - type: textarea  
    id: steps-to-reproduce  
    attributes:
      label: "Steps to Reproduce"
      description: "How can we reproduce this issue?"
      placeholder: |
        1. Go to...
        2. Click on...
        3. See the error...
    validations:
      required: true  
  - type: textarea  
    id: expected-result  
    attributes:
      label: "Expected vs. Actual Result"
      description: "What did you expect to happen?"
      placeholder: "I expected..."
  - type: dropdown  
    id: browser  
    attributes:
      label: "Which browser are you using?"
      options:
        - Chrome  
        - Firefox  
        - Safari  
        - Edge  
        - Other