name: Feature Request  
description: Suggest a new feature  
title: "[Feature] "  
labels: ["enhancement"]  
body:
  - type: input  
    id: feature-title  
    attributes:
      label: "Feature Title"
      placeholder: "What is the feature about?"
    validations:
      required: true  
  - type: textarea  
    id: feature-description  
    attributes:
      label: "Feature Description"
      description: "Describe the feature in detail"
      placeholder: "I would like this feature because..."